### ISSUE TITLE
Deep Dungeon Clear Roles

### ISSUE THREAD

**Issue by brtran4** [Veraticus/clearingway#2]
Not in fflogs but maybe can bind to achievements

**Comment by brtran4** [comment]
we should probably figure out to what extent we should have these roles (how many clears, etc)

**Comment by ghost** [comment]
Can only track the initial clear with achievements. Can only find if the user DOES NOT have achievements private via lodestone. Might wanna make a prompt or document it.

Each DD is listed below with the achieve needed to be counted as cleared solo. Title is also listed. I say make the role the title.

PoTD

- Pal-less Palace III
- The Necromancer

HoH

- Heaven Is a Lonely Place II
- Lone Hero
- 

EO

- All by Eurekaself II
- Once and Future King  /  Queen

**Comment by joshsymonds** [comment]
The primary problem with detecting achievements from the website is that IPs get hardcore rate limited to the FFXIV site. We can try it but we have to work to keep requests to a minimum or else we'll be denylisted.

**Comment by ghost** [comment]
> The primary problem with detecting achievements from the website is that IPs get hardcore rate limited to the FFXIV site. We can try it but we have to work to keep requests to a minimum or else we'll be denylisted.

We wouldn't be pulling this info from the Lodestone, we would be pulling from https://ffxivcollect.com
@Veraticus

**Comment by brtran4** [comment]
> Can only track the initial clear with achievements. Can only find if the user DOES NOT have achievements private via lodestone. Might wanna make a prompt or document it.
> 
> Each DD is listed below with the achieve needed to be counted as cleared solo. Title is also listed. I say make the role the title.
> 
> PoTD
> 
> * Pal-less Palace III
> * The Necromancer
> 
> HoH
> 
> * Heaven Is a Lonely Place II
> * Lone Hero
> 
> EO
> 
> * All by Eurekaself II
> * Once and Future King  /  Queen

@clairwastaken Since https://ffxivcollect.com/ won't work, we should probably make some text to tell the user to unprivate their achievements

**Comment by ghost** [comment]
@brtran4 could just add a task to see if achievements are private are not. If private, have clearingway return that they need to turn achievements public to get DD roles.

**Comment by brtran4** [comment]
roles currently look as
<img width="709" alt="Screenshot 2024-02-19 at 4 05 07 AM" src="https://github.com/Veraticus/clearingway/assets/44913669/8e448edf-5e63-472f-a43b-a5e3f6ea0866">

**Comment by ghost** [comment]
@brtran4 does this still need to be open.

**Comment by brtran4** [comment]
> @brtran4 does this still need to be open.

Yes since we will switch to tomestonegg and we have to wait for their api to update to include achievements

**Comment by brtran4** [comment]
closing as the roles are made. will make a new issue to use tomestonegg api
